# Generated by Django 3.2.7 on 2021-09-21 09:22

from django.db import migrations, models
import ses_email.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=ses_email.models.random_string, max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
